api = "0.4"

[buildpack]
id = "heroku/procfile"
version = "0.8.0"
name = "Procfile"
homepage = "https://github.com/heroku/procfile-cnb"
description = "Official Heroku buildpack for using Procfile."
keywords = ["procfile", "processes"]

[[stacks]]
id = "*"

[[buildpack.licenses]]
type = "BSD-3-Clause"
