[package]
name = "procfile-buildpack"
version = "0.1.0"
authors = ["Richard Schneeman <richard.schneeman@gmail.com>"]
edition = "2021"
rust-version = "1.56"

[dependencies]
libcnb = "0.3.0"
thiserror = "1.0"
yaml-rust = "0.4"
termcolor = "1.1.2"

[dev-dependencies]
assert_matches = "1.5.0"
tempfile = "^3.2.0"
toml = "^0.5.8"
