[package]
name = "procfile-buildpack"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
libcnb = "0.5.0"
libherokubuildpack = "0.5.0"
thiserror = "1.0.30"
yaml-rust = "0.4.5"

[dev-dependencies]
tempfile = "3.3.0"
