[package]
name = "procfile-buildpack"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
libcnb = "0.4.0"
thiserror = "1.0"
yaml-rust = "0.4"
libherokubuildpack = "0.4.0"

[dev-dependencies]
tempfile = "^3.3.0"
