[package]
name = "procfile-buildpack"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
indoc = "1.0.3"
libcnb = "0.5.0"
libherokubuildpack = "0.5.0"
linked-hash-map = "0.5.4"
thiserror = "1.0.30"
yaml-rust = "0.4.5"

[dev-dependencies]
tempfile = "3.3.0"
libcnb-test = "0.1.0"
ureq = "2.4.0"
